spring.application.name=EtlVotacion

# ======================
# SERVER
# ======================
server.port=${PORT:8083}

# ======================
# PostgreSQL (mismo que VotacionBack y RegistraduriaBack)
# ======================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ======================
# SPRING BATCH
# ======================
# No ejecutar el job al arrancar — solo bajo demanda via POST /etl/ejecutar
spring.batch.job.enabled=false
# Crear las tablas de metadata de Spring Batch automáticamente en PostgreSQL
spring.batch.jdbc.initialize-schema=always

# ======================
# COUCHDB
# ======================
couchdb.url=${COUCHDB_URL:http://localhost:5984}
couchdb.username=${COUCHDB_USER:admin}
couchdb.password=${COUCHDB_PASSWORD:admin}
couchdb.database.urna=${COUCHDB_DB_URNA:votos_urna}
couchdb.database.domicilio=${COUCHDB_DB_DOMICILIO:votos_domicilio}

# ======================
# LOGGING
# ======================
logging.level.org.springframework.batch=${LOG_LEVEL_BATCH:INFO}
logging.level.org.springframework=${LOG_LEVEL:WARN}
